---
account_cli_password: temp12345
root_account_mnemonic: "measure awful such forum fringe urban suggest cancel allow pretty border sense talk plastic mule crouch fancy nurse lottery system maximum ceiling proud nurse"
