#
# Copyright 2019-20 Wireline, Inc.
#

---
account_cli_password: temp12345
root_account_mnemonic: "adjust diary sibling toilet major novel sauce crater action ancient egg avoid test still robot carpet happy hedgehog coyote patrol code assist worth rug"
