name: WNS Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: make install
      run: |
        mkdir -p `pwd`/go/bin
        export GOPATH="`pwd`/go"
        export PATH="$PATH:$GOBIN"
        export GO111MODULE=on
        export GOOS="linux"
        mkdir dist
        
        export GOARCH="amd64"
        rm -rf build
        make install
        mkdir -p build/bin/
        mv go/bin/* build/bin/
        cp -r scripts devnet README.md build/
        zip -r dist/wns-linux-x64.zip build/
        

        export GOARCH="arm64"
        rm -rf build
        make install
        mkdir -p build/bin/
        mv go/bin/linux_arm64/* build/bin/
        cp -r scripts devnet README.md build/
        zip -r dist/wns-linux-arm64.zip build/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset x64
      id: upload-release-asset-x64 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/wns-linux-x64.zip
        asset_name: wns-linux-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset arm64
      id: upload-release-asset-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./dist/wns-linux-arm64.zip
        asset_name: wns-linux-arm64.zip
        asset_content_type: application/zip
